#:schema node_modules/wrangler/config-schema.json
name = "onesource-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# [d1_databases]
# binding = "DB"
# database_name = "onesource-db"
# database_id = "YOUR_DATABASE_ID"

# [vars]
# STRIPE_PUBLISHABLE_KEY = "..."
# STRIPE_PRICE_ID = "..."
