#:schema node_modules/wrangler/config-schema.json
name = "onesource-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "onesource-db"
database_id = "a6249331-c31e-4327-b935-562c8b286e9b"

# [vars]
# STRIPE_PUBLISHABLE_KEY = "..."
# STRIPE_PRICE_ID = "..."
